print ("hello!")
name=input("What is your name?")
print("Welcome", name)
location=input("Where are you from?")
color=input("What is your favorite color?")
age=input("How old are you?")
print("Nice to meet you", name, "from", location)
print("It's so cool that a", age, "year old likes", color)
